secrets:
    github-token:
        description: Github Personal Access github-token
        type: usernamePassword
        stringData:
            password: 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
            username: darlaig