{{- range $name, $s := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    jenkins.io/credentials-type: {{ $s.type }}
  annotations:
    jenkins.io/credentials-description: {{ $s.description }}
type: Opaque
stringData:
{{ toYaml $s.stringData | indent 2 }}
{{ end }}