
node('jenkins-slave') {
    
     stage('test pipeline') {
        sh(script: """
            echo "hello"
           git clone https://github.com/darlaig/test-k8s.git
           cd docker-development-youtube-series/golang
           
           docker build . -t test
        """)
    }
}


pipeline {
  agent {
    kubernetes {
      yaml '''
        apiVersion: v1
        kind: Pod
        metadata:
          name: jenkins-slave
          labels:
            app: jenkins-slave
        spec:
          serviceAccountName: jenkins
          containers:
            - name: smd-worker-cypress
              image: 635081340056.dkr.ecr.eu-west-1.amazonaws.com/test:cypress-custom-8.7.0
              imagePullPolicy: Always
              command: ['cat']
              args: 
              tty: true
        '''
    }
  }