apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-api
  namespace: nginx
subjects:
- kind: ServiceAccount
  name: nginx-api
roleRef:
  kind: Role
  name: nginx-api
  apiGroup: rbac.authorization.k8s.io