apiVersion: v1
kind: Secret
metadata:
    name: api-key
    namespace: nginx
data:
    API_KEY: ENC[AES256_GCM,data:K1dYayOFJ+Qas/JOqZ9OZQ==,iv:WeN6dQMFOUQdxB7QnjiVMzAPQtOsLZ+YEda60lrNGLI=,tag:Ry77nRZ1ql3QvWlDOVQyKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-05-10T12:06:37Z"
    mac: ENC[AES256_GCM,data:714ZK+aE5dRIe2yoYBlRBXP4GyByILuU8D9cjMW6X/t+lk2F89v3yl1OqWWqZwLKlixhMgis1dS4p7yCMOWUeJvxg/AqqvaBDORjTd78l2gYTwzFgtdEoiOC710/PxyvEmspd0UYNoLb+2lty56t/LAy5YPHrRZhaD4naQi6twM=,iv:Nrl7yb0W9Pgo2K2fBmRR5Dafz7DhzCnYc5LtywgHTa4=,tag:3HCEsS2ng+Xehd0yguNWtA==,type:str]
    pgp:
        - created_at: "2022-05-10T12:06:36Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA5cjBqxIx0TYAQv/bQrYjs6/0Dk5A778qeDObyaEDf0IdYqrbinE9W6vUhh0
            SJCB3kIuthKPn06WfyHdw2Cuj0tlZzOYkW/6ykOkhUVHa+wnWDJx0sCk+7uu/5h4
            SuX9WzQGMEk8AwvDjgNMQvWSM7dGq9Hr3S7lhTsfrdtRem/LhYpPpAYQk1E6zs2R
            ol5oCSRtjrqFWOVPi+nXHIiOkxB0dcVzsBgln5Na5C2k5J4kR/Zcp0bjGnIlBlkh
            vL5SW3N+rKSxlZ4LcyCpRsjHP0Xrcv0mxqoGOYlGzWkq9I3O1KAhaQ6oO4RSRztd
            QCtfyM0AtycET3uGZzB7+iLyOQs+7ZmgiBd18xm/8GbyVOYZ1lhRMMVr/dtzx0Q1
            0mikyniKeCW2t1lMZjOLvX6AHH5smf/pDWjxx1EiLPSCL5wx8x1v/9tsqRS3v/i8
            9p1+Qn6/46ecYc9XNfIRwMQw3xvi3acdjCOIE4FlKQfo5mDKArt8/o0sXUz12ZTs
            xYR3dBHUSoJ65bAAR6Dw1GYBCQIQy10z7K5tf0W6pPSCj3/hwzhxMEAjEkIjnujN
            LJAdHbS+Duc8wQ+hj2WxA33stjAy5aXXrY7f28qApYtB8/iVRkEpgqk9U8QspQGD
            2AFAV8bN4+QC/26q4R2h5NEoSyUxF4c=
            =R6VX
            -----END PGP MESSAGE-----
          fp: 04A906AE1240F443504B89AA75102E0B65B2F67A
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
