apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-api
  namespace: nginx

---  

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: nginx
  name: nginx-api
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]