apiVersion: v1
kind: ServiceAccount
metadata:
  name: shopping-api

---  

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: web-app
  name: shopping-api
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]