pipeline {
  agent { labels 'jenkins-slave' }
  environment {
    IMAGE_NAME = 'myapp/test'
  }

  stages {

    stage('Checkout')
      steps {
        checkout([$class: 'GitSCM', branches: [[name: '**']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/darlaig/test-k8s.git']]])
        script {
          sh 'cd ./python '
        }
      }
    }

    stage('Build') {
      steps {
        script {
          sh 'docker build -t ${IMAGE_NAME} .'
        }
      }
    }

    stage('Image Scan') {
      steps {
        script {
          sh ' trivy image ${IMAGE_NAME}'
        }
      }
    }
  }
}