pipeline {
  agent any
  environment {
    IMAGE_NAME = 'myapp/test'
  }

  stages {

    stage('Checkout')
      steps {
        script {
          sh 'rm -rf *;git clone https://github.com/darlaig/test-k8s.git'
          sh 'cd ./python '
        }
      }
    }

    stage('Build') {
      steps {
        script {
          sh 'docker build -t ${IMAGE_NAME} .'
        }
      }
    }

    stage('Image Scan') {
      steps {
        script {
          sh ' trivy image ${IMAGE_NAME}'
        }
      }
    }
  }
}